# Generated by Django 4.0.3 on 2022-04-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ikinciuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IkinciUser',
        ),
    ]
